# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby on Rails

on:
  push:
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:
    branches: [ $default-branch ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: rbp_basic_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Setup config files
        run: |
          cp -f config/app_config.rb.ci config/app_config.rb
          cp -f config/app.yml.ci config/app.yml
          cp -f config/database.yml.ci config/database.yml
          cp -f config/cable.yml.ci config/cable.yml
          cp -f config/storage.yml.ci config/storage.yml
          cp package.json.template package.json
          cp config/importmap.rb.template config/importmap.rb
          cp config/i18n-tasks.yml.template config/i18n-tasks.yml
      - name: Run rubocop
        run: bundle exec rake rubocop:changed
      - name: Setup database
        env:
          RAILS_ENV: test
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: rbp_basic_test
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        run: |
          bundle exec rails db:create
          bundle exec rails db:schema:load
      - name: Check application can be eager loaded
        env:
          RAILS_ENV: test
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: rbp_basic_test
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        run: bundle exec rake zeitwerk:check
      - name: Install Yarn & modules
        run: |
          npm install -g yarn
          yarn install
      - name: Build assets
        env:
          RAILS_ENV: test
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: rbp_basic_test
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        run: bundle exec rails dartsass:build
      - name: Run tests
        env:
          RAILS_ENV: test
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: rbp_basic_test
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        run: bundle exec rspec
      - name: Audit bundle for vulnerabilities
        run: bundle exec bundle-audit
      - name: Audit impormaps for vulnerabilities
        run: bundle exec bin/importmap audit
